#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_dir="$repo_root/artifacts"
usbroot="$out_dir/usbroot"
iso_root="$out_dir/iso-root"
iso_path="$out_dir/dekasigna-uefi.iso"
zip_path="$out_dir/dekasigna-uefi.zip"

mkdir -p "$usbroot/EFI/Boot" "$usbroot/EFI/BOOT" "$usbroot/boot/grub" "$usbroot/tools" "$usbroot/lab/mock-uefi-acpi" "$usbroot/lab/hackintosh-9470m" "$usbroot/lab/libreboot" "$usbroot/validation" "$usbroot/validation/ms-uefi-validation" "$usbroot/windows"
mkdir -p "$iso_root/EFI/Boot" "$iso_root/EFI/BOOT" "$iso_root/boot/grub" "$iso_root/tools" "$iso_root/lab/mock-uefi-acpi" "$iso_root/lab/hackintosh-9470m" "$iso_root/lab/libreboot" "$iso_root/validation" "$iso_root/validation/ms-uefi-validation" "$iso_root/windows"

cp "$repo_root/tools/uefi/Shell.efi" "$usbroot/tools/Shell.efi"
cp "$repo_root/tools/uefi/Shell.efi" "$usbroot/EFI/Boot/Bootx64.efi"
cp "$repo_root/tools/uefi/Shell.efi" "$usbroot/EFI/BOOT/BOOTX64.EFI"
cp "$repo_root/tools/uefi/Shell.efi" "$iso_root/tools/Shell.efi"
cp "$repo_root/tools/uefi/Shell.efi" "$iso_root/EFI/Boot/Bootx64.efi"
cp "$repo_root/tools/uefi/Shell.efi" "$iso_root/EFI/BOOT/BOOTX64.EFI"
cp "$repo_root/tools/uefi/AutoSecureBootFix.nsh" "$usbroot/"
cp "$repo_root/tools/uefi/AutoSecureBootFix.nsh" "$iso_root/"
cp "$repo_root/tools/uefi/FactoryFirmwarePatch.nsh" "$usbroot/"
cp "$repo_root/tools/uefi/FactoryFirmwarePatch.nsh" "$iso_root/"
cp "$repo_root/tools/uefi/UpdateKeys.nsh" "$usbroot/"
cp "$repo_root/tools/uefi/UpdateKeys.nsh" "$iso_root/"
cp "$repo_root/tools/uefi/usb-layout.txt" "$usbroot/"
cp "$repo_root/tools/uefi/usb-layout.txt" "$iso_root/"
cp "$repo_root/tools/uefi/grub.cfg" "$usbroot/boot/grub/grub.cfg"
cp "$repo_root/tools/uefi/grub.cfg" "$iso_root/boot/grub/grub.cfg"
cp "$repo_root/generators/hp-customer-keys.sh" "$usbroot/tools/"
cp "$repo_root/generators/hp-customer-keys.sh" "$iso_root/tools/"
cp "$repo_root/generators/usermode-pk.sh" "$usbroot/tools/"
cp "$repo_root/generators/usermode-pk.sh" "$iso_root/tools/"
cp "$repo_root/validation/run-validation.ps1" "$usbroot/tools/"
cp "$repo_root/validation/run-validation.ps1" "$iso_root/tools/"
cp "$repo_root/validation/README.md" "$usbroot/validation/"
cp "$repo_root/validation/README.md" "$iso_root/validation/"
cp "$repo_root/validation/ms-uefi-validation/README.md" "$usbroot/validation/ms-uefi-validation/"
cp "$repo_root/validation/ms-uefi-validation/README.md" "$iso_root/validation/ms-uefi-validation/"
cp "$repo_root/windows/block-ms-dbx.ps1" "$usbroot/windows/"
cp "$repo_root/windows/block-ms-dbx.ps1" "$iso_root/windows/"
cp "$repo_root/windows/fix-secureboot-update.ps1" "$usbroot/windows/"
cp "$repo_root/windows/fix-secureboot-update.ps1" "$iso_root/windows/"
cp "$repo_root/windows/hp-9470m-secureboot-checklist.ps1" "$usbroot/windows/"
cp "$repo_root/windows/hp-9470m-secureboot-checklist.ps1" "$iso_root/windows/"
cp "$repo_root/windows/query-version-and-status.ps1" "$usbroot/windows/"
cp "$repo_root/windows/query-version-and-status.ps1" "$iso_root/windows/"
cp "$repo_root/windows/rufus-write-assist.ps1" "$usbroot/windows/"
cp "$repo_root/windows/rufus-write-assist.ps1" "$iso_root/windows/"
cp "$repo_root/windows/log-secureboot-memory-integrity.ps1" "$usbroot/windows/"
cp "$repo_root/windows/log-secureboot-memory-integrity.ps1" "$iso_root/windows/"
cp "$repo_root/windows/hackintosh-9470m-lab-report.ps1" "$usbroot/windows/"
cp "$repo_root/windows/hackintosh-9470m-lab-report.ps1" "$iso_root/windows/"
cp "$repo_root/windows/local-lab-report.ps1" "$usbroot/windows/"
cp "$repo_root/windows/local-lab-report.ps1" "$iso_root/windows/"
cp "$repo_root/windows/libreboot-lab-report.ps1" "$usbroot/windows/"
cp "$repo_root/windows/libreboot-lab-report.ps1" "$iso_root/windows/"
cp "$repo_root/windows/libreboot-risk-score.ps1" "$usbroot/windows/"
cp "$repo_root/windows/libreboot-risk-score.ps1" "$iso_root/windows/"
cp "$repo_root/windows/verify-secureboot.ps1" "$usbroot/windows/"
cp "$repo_root/windows/verify-secureboot.ps1" "$iso_root/windows/"
cp "$repo_root/README.md" "$usbroot/README.txt"
cp "$repo_root/README.md" "$iso_root/README.txt"
cp "$repo_root/lab/mock-uefi-acpi/README.md" "$usbroot/lab/mock-uefi-acpi/"
cp "$repo_root/lab/mock-uefi-acpi/README.md" "$iso_root/lab/mock-uefi-acpi/"
cp "$repo_root/lab/mock-uefi-acpi/mock-device-tree.asl" "$usbroot/lab/mock-uefi-acpi/"
cp "$repo_root/lab/mock-uefi-acpi/mock-device-tree.asl" "$iso_root/lab/mock-uefi-acpi/"
cp "$repo_root/lab/mock-uefi-acpi/mock-uefi-device.json" "$usbroot/lab/mock-uefi-acpi/"
cp "$repo_root/lab/mock-uefi-acpi/mock-uefi-device.json" "$iso_root/lab/mock-uefi-acpi/"
cp "$repo_root/lab/hackintosh-9470m/README.md" "$usbroot/lab/hackintosh-9470m/"
cp "$repo_root/lab/hackintosh-9470m/README.md" "$iso_root/lab/hackintosh-9470m/"
cp "$repo_root/lab/hackintosh-9470m/compatibility-template.md" "$usbroot/lab/hackintosh-9470m/"
cp "$repo_root/lab/hackintosh-9470m/compatibility-template.md" "$iso_root/lab/hackintosh-9470m/"
cp "$repo_root/lab/libreboot/README.md" "$usbroot/lab/libreboot/"
cp "$repo_root/lab/libreboot/README.md" "$iso_root/lab/libreboot/"
cp "$repo_root/lab/libreboot/flash-workflow.md" "$usbroot/lab/libreboot/"
cp "$repo_root/lab/libreboot/flash-workflow.md" "$iso_root/lab/libreboot/"
cp "$repo_root/lab/libreboot/risk-matrix.md" "$usbroot/lab/libreboot/"
cp "$repo_root/lab/libreboot/risk-matrix.md" "$iso_root/lab/libreboot/"

rm -f "$iso_path" "$zip_path"
rm -rf "$iso_root"
mkdir -p "$iso_root/EFI/Boot" "$iso_root/EFI/BOOT" "$iso_root/boot/grub" "$iso_root/tools" "$iso_root/lab/mock-uefi-acpi" "$iso_root/lab/hackintosh-9470m" "$iso_root/lab/libreboot" "$iso_root/validation" "$iso_root/validation/ms-uefi-validation" "$iso_root/windows"
cp -a "$usbroot"/. "$iso_root"/
cp "$repo_root/tools/uefi/grub.cfg" "$iso_root/boot/grub/grub.cfg"
cp "$repo_root/tools/uefi/Shell.efi" "$iso_root/tools/Shell.efi"
cp "$repo_root/tools/uefi/Shell.efi" "$iso_root/EFI/BOOT/BOOTX64.EFI"
cp "$repo_root/tools/uefi/Shell.efi" "$iso_root/EFI/Boot/Bootx64.efi"

xorriso -indev stdio:/dev/zero -outdev stdio:"$iso_path" -blank as_needed -map "$iso_root" / -boot_image any partition_table=on -boot_image any efi_path=EFI/BOOT/BOOTX64.EFI >/dev/null

(cd "$out_dir" && zip -r "dekasigna-uefi.zip" "usbroot" "dekasigna-uefi.iso" >/dev/null)

echo "Built $iso_path and $zip_path"
